import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { User } from "@/Services/group";

const slice = createSlice({
  name: "userList",
  initialState: {
    userList: [
      {
          "id": 2,
          "name": "Thi ne",
          "dateofbirth": null,
          "email": "lsjenny1710+200@gmail.com",
          "password": "$2b$10$2RTzkFRVwu4tL9.Thr6KJOEE1JECkYfe8mFcKQJ4IVeMWL.ggMqoi",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-15T10:55:32.299Z",
          "updatedAt": "2024-12-15T10:55:47.804Z",
          "isActive": true,
          "isEmailVerified": true,
          "verificationCode": null,
          "verificationCodeExpiresAt": null,
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 3,
          "name": "Thi thi thi",
          "dateofbirth": null,
          "email": "thi.phanpham+200@hcmut.edu.vn",
          "password": "$2b$10$gUGr.EoUL7vKvT0H2xQ1MuSG4qIEJaLdPRNLAfbc81ZFfKPfKSm9e",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-15T11:13:14.033Z",
          "updatedAt": "2024-12-15T11:13:14.033Z",
          "isActive": true,
          "isEmailVerified": false,
          "verificationCode": "415602",
          "verificationCodeExpiresAt": "2024-12-15T11:28:13.863Z",
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 5,
          "name": "Hihi",
          "dateofbirth": null,
          "email": "lsjenny1710+101@gmail.com",
          "password": "$2b$10$IytUO6LUPOp5jxQuy4/H3.F4v/vZF.N622LepaYxeqnqyPxuOgI5e",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-15T11:24:31.741Z",
          "updatedAt": "2024-12-15T11:25:02.903Z",
          "isActive": true,
          "isEmailVerified": true,
          "verificationCode": null,
          "verificationCodeExpiresAt": null,
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 7,
          "name": "--",
          "dateofbirth": null,
          "email": "thi.phanpham+103@hcmut.edu.vn",
          "password": "$2b$10$P5i30qxqA0zeEj9yrFsoX.cSdDC28G/S6LQomRwHRuxFRSzOnYWlu",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-15T12:42:35.687Z",
          "updatedAt": "2024-12-15T12:43:33.293Z",
          "isActive": true,
          "isEmailVerified": true,
          "verificationCode": null,
          "verificationCodeExpiresAt": null,
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 6,
          "name": "--",
          "dateofbirth": null,
          "email": "thi.phanpham+102@hcmut.edu.vn",
          "password": "$2b$10$sS4DnHEkOTUY1qbbR3/dSeahLVhrFl3YkB4u0krI7X4OkOx9w2Ep6",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-15T12:29:29.593Z",
          "updatedAt": "2024-12-15T12:53:12.479Z",
          "isActive": true,
          "isEmailVerified": false,
          "verificationCode": "757121",
          "verificationCodeExpiresAt": "2024-12-15T13:08:12.397Z",
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 4,
          "name": "Thi thi thi",
          "dateofbirth": null,
          "email": "thi.phanpham@hcmut.edu.vn",
          "password": "$2b$10$86XdFJ8OOVHAzGOxd8m5h.Hq9VatEbwCgUinvVufnkAOgXr96APjC",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-15T11:16:57.043Z",
          "updatedAt": "2024-12-15T12:59:54.392Z",
          "isActive": true,
          "isEmailVerified": false,
          "verificationCode": "208277",
          "verificationCodeExpiresAt": "2024-12-15T13:14:54.310Z",
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 8,
          "name": " Tt",
          "dateofbirth": null,
          "email": "lsjenny1710+1@gmail.com",
          "password": "$2b$10$kZSPFAogfTWrkmY4GzhLo.KKzt4os5Mqw5fSPyS1KmJUEnZD9HT/S",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-15T13:34:41.588Z",
          "updatedAt": "2024-12-15T14:01:52.380Z",
          "isActive": true,
          "isEmailVerified": true,
          "verificationCode": null,
          "verificationCodeExpiresAt": null,
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 10,
          "name": "string",
          "dateofbirth": null,
          "email": "ledinhhuy155@gmail.com",
          "password": "$2b$10$9iDvVkqW/7vYH3z85YdHCu2WbgQKtrC3oqUcwMjZ062IrppPyPG/m",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-16T02:43:23.629Z",
          "updatedAt": "2024-12-16T02:43:23.629Z",
          "isActive": true,
          "isEmailVerified": false,
          "verificationCode": "777181",
          "verificationCodeExpiresAt": "2024-12-16T02:58:23.549Z",
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 9,
          "name": "Lê Đình Huy",
          "dateofbirth": "2028-12-20T08:53:19.000Z",
          "email": "huy.ledinh@hcmut.edu.vn",
          "password": "$2b$10$lwQBXZakcg6eqaXwQoyXEeaSYfh4sXmDfKBBJti0qSHk5KNQPKOAu",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-16T02:12:02.818Z",
          "updatedAt": "2024-12-20T08:53:24.986Z",
          "isActive": true,
          "isEmailVerified": true,
          "verificationCode": null,
          "verificationCodeExpiresAt": null,
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      },
      {
          "id": 1,
          "name": "Tuan Nguyen 1",
          "dateofbirth": "2003-05-16T07:00:00.000Z",
          "email": "nguyenducanhtuan0602@gmail.com",
          "password": "$2b$10$xBmGZ9waMSodhC.yQkfACu9NFkPIxH6Zo2rw1ZItDNrIJDj4SWkMS",
          "group_id": null,
          "joined_at": null,
          "role": null,
          "createdAt": "2024-12-11T03:43:08.432Z",
          "updatedAt": "2024-12-20T10:17:43.475Z",
          "isActive": true,
          "isEmailVerified": true,
          "verificationCode": null,
          "verificationCodeExpiresAt": null,
          "status": "OFFLINE",
          "passwordResetCode": null,
          "passwordResetCodeExpiresAt": null
      }
  ] as User[],
  },
  reducers: {
    setUserList: (state, action: PayloadAction<User[]>) => {
      state.userList = action.payload;
    },
  },
});

export const { setUserList } = slice.actions;

export const userListReducers = slice.reducer;
